//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverSLAJob
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CRMORIGINEntities : DbContext
    {
        public CRMORIGINEntities()
            : base("name=CRMORIGINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CaseLogs> CaseLogs { get; set; }
        public DbSet<Cases> Cases { get; set; }
        public DbSet<TaskScheduleLog> TaskScheduleLog { get; set; }
    
        public virtual ObjectResult<sp_getCasesOverSLA_Result> sp_getCasesOverSLA(string p_Now)
        {
            var p_NowParameter = p_Now != null ?
                new ObjectParameter("p_Now", p_Now) :
                new ObjectParameter("p_Now", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getCasesOverSLA_Result>("sp_getCasesOverSLA", p_NowParameter);
        }
    }
}
