//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityStatus
    {
        public ActivityStatus()
        {
            this.ActivityStatus_Locale = new HashSet<ActivityStatus_Locale>();
        }
    
        public int atsID { get; set; }
        public bool atsActive { get; set; }
        public System.DateTime atsModifiedOn { get; set; }
        public int atsModifiedBy { get; set; }
    
        public virtual ICollection<ActivityStatus_Locale> ActivityStatus_Locale { get; set; }
    }
}
