//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int casID { get; set; }
        public int actID { get; set; }
        public int ctaID { get; set; }
        public string casIDName { get; set; }
        public Nullable<int> casParentID { get; set; }
        public Nullable<int> casDuration { get; set; }
        public Nullable<System.DateTime> casDueDate { get; set; }
        public Nullable<System.DateTime> casPrevDueDate { get; set; }
        public Nullable<int> casIDLevel1 { get; set; }
        public Nullable<int> casIDLevel2 { get; set; }
        public Nullable<int> casIDLevel3 { get; set; }
        public Nullable<int> casIDLevel4 { get; set; }
        public Nullable<int> casIDLevel5 { get; set; }
        public Nullable<int> casIDLevel6 { get; set; }
        public Nullable<int> casIDLevel7 { get; set; }
        public Nullable<int> casIDLevel8 { get; set; }
        public string casLevel1 { get; set; }
        public string casLevel2 { get; set; }
        public string casLevel3 { get; set; }
        public string casLevel4 { get; set; }
        public string casLevel5 { get; set; }
        public string casLevel6 { get; set; }
        public string casLevel7 { get; set; }
        public string casLevel8 { get; set; }
        public int casIDSummary { get; set; }
        public string casSummary { get; set; }
        public string casNote { get; set; }
        public Nullable<int> cbtID { get; set; }
        public Nullable<int> cbcID { get; set; }
        public string CallbackInfo { get; set; }
        public Nullable<System.DateTime> CallbackDT { get; set; }
        public Nullable<int> casSLA { get; set; }
        public int priID { get; set; }
        public int cssID { get; set; }
        public Nullable<int> casEmo { get; set; }
        public Nullable<int> casGroupID { get; set; }
        public Nullable<int> casOwnerID { get; set; }
        public System.DateTime casCreatedOn { get; set; }
        public int casCreatedBy { get; set; }
        public System.DateTime casModifiedOn { get; set; }
        public int casModifiedBy { get; set; }
        public bool casFav { get; set; }
        public Nullable<int> assignTo { get; set; }
        public Nullable<int> casRemindID { get; set; }
        public string casRemindStatus { get; set; }
        public string cascommerceType { get; set; }
        public string casproductCategory { get; set; }
        public string casserviceCategory { get; set; }
        public string casdeliveryType { get; set; }
        public string casvalueRange { get; set; }
        public string casconversationChannel { get; set; }
        public string casreferenceDetail { get; set; }
        public string casdetail { get; set; }
        public string casstatusReason { get; set; }
        public string caspaymentType { get; set; }
        public string casVendorID { get; set; }
        public Nullable<System.DateTime> caseventDate { get; set; }
        public string casAttachFile { get; set; }
        public string casPoNo { get; set; }
        public string casPrice { get; set; }
    }
}
