//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationType
    {
        public int nttID { get; set; }
        public string nttName { get; set; }
        public bool nttActive { get; set; }
        public System.DateTime nttModifiedOn { get; set; }
        public int nttModifiedBy { get; set; }
    }
}
