//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneType_Locale
    {
        public int phtID { get; set; }
        public string lclID { get; set; }
        public string phtName { get; set; }
        public System.DateTime phtModifiedOn { get; set; }
        public int phtModifiedBy { get; set; }
    
        public virtual Locale Locale { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
