//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEWCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priority_Locale
    {
        public int priID { get; set; }
        public string lclID { get; set; }
        public string priName { get; set; }
        public System.DateTime priModifiedOn { get; set; }
        public int priModifiedBy { get; set; }
    }
}
